name: Deploy Images to GHCR

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub repo"
        uses: actions/checkout@v3

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.MY_SECRET}}

      - name: "Build Inventory Image"
        run: |
          docker build . --tag ghcr.io/arletteT/hello-world:latest
          docker push ghcr.io/arletteT/hello-world:latest
